# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brenden Sosnader
email: brendensosnader@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Brenden Sosnader. I'm a recent Penn State graduate with degrees in Computer Science and Statistics. I will begin working for Microsoft in Redmond, WA as a software engineer in July. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sosnader.com" # the base hostname & protocol for your site
twitter_username: bsosnader
github_username:  bsosnader

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
sass:
  style: compressed
